DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES(
 EMPLOYEE_ID SERIAL PRIMARY KEY,
 FIRST_NAME VARCHAR(50) NOT NULL,
 LAST_NAME VARCHAR(50) NOT NULL,
 DEPARTMENT VARCHAR(50),
 SALARY NUMERIC(10,2) CHECK(SALARY>0),
 JOINING_DATE DATE NOT NULL,
 AGE INT CHECK(AGE>=18),
 EMAIL VARCHAR(100) UNIQUE
);	
INSERT INTO EMPLOYEES(FIRST_NAME,LAST_NAME,DEPARTMENT,SALARY,JOINING_DATE,AGE)
VALUES('AMIT','SHARMA','IT',60000.00,'2003-01-21',29),
      ('NEHA','PATEL','HR',55000.00,'2002-01-23',40),
	  ('RAVI','KUMAR','FINANCE',70000.00,'2005-5-2',32),
      ('ANJALI','VERMA','IT',65000.00,'2002-07-22',30),
	  ('SURESH','REDDY','OPERATIONS',50000.00,'2002-05-12',29);
SELECT*FROM EMPLOYEES ORDER BY EMPLOYEE_ID ASC;      
SELECT FIRST_NAME,DEPARTMENT FROM EMPLOYEES;	  
UPDATE EMPLOYEES
SET SALARY=SALARY+(SALARY*0.10)
WHERE DEPARTMENT='IT';
DELETE FROM EMPLOYEES
WHERE AGE>34;
ALTER TABLE EMPLOYEES
RENAME COLUMN DEPARTMENT TO DEPT_NAME;
SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES WHERE JOINING_DATE>'2002-07-22';
ALTER TABLE EMPLOYEES
ALTER COLUMN SALARY TYPE INTEGER;
SELECT AGE,SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
UPDATE EMPLOYEES
SET AGE=AGE+1 ;


