DROP TABLE IF EXISTS EMPLOYEE2;
CREATE TABLE EMPLOYEE2(
 EMPLOYEE_ID INT PRIMARY KEY,
 FIRST_NAME VARCHAR(20) NOT NULL,
 LAST_NAME VARCHAR(20) NOT NULL,
 EMAIL VARCHAR(50),
 DEPARTMENT VARCHAR(50),
 SALARY NUMERIC(10,2),
 JOINING_DATE  DATE,
 AGE INT 
);
SELECT*FROM EMPLOYEE2; 
SELECT FIRST_NAME, SALARY,(SALARY*0.10) AS BONUS FROM EMPLOYEE2;
SELECT FIRST_NAME, SALARY ,
       (SALARY*12) AS ANNUAL_SALARY,
       (SALARY*0.05) AS INCREMENTED_SALARY,
	   (SALARY+SALARY*0.05) AS NEW_SALARY  
FROM EMPLOYEE2;	   

SELECT*FROM EMPLOYEE2
WHERE AGE=30;
SELECT FIRST_NAME, AGE FROM EMPLOYEE2
WHERE AGE!=30;
SELECT*FROM EMPLOYEE2
WHERE SALARY>50000;

SELECT*FROM EMPLOYEE2
WHERE AGE>=50 AND SALARY>=50000;
SELECT*FROM EMPLOYEE2
WHERE AGE>=50 OR SALARY>=90000;
SELECT*FROM EMPLOYEE2 
WHERE NOT (DEPARTMENT='IT');
SELECT * FROM  EMPLOYEE2
WHERE DEPARTMENT='Finance' OR DEPARTMENT='Marketing';

SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEE2
WHERE SALARY BETWEEN 40000 AND 60000;

SELECT FIRST_NAME,LAST_NAME,SALARY,EMAIL FROM EMPLOYEE2
WHERE EMAIL LIKE '%gmail.com';

SELECT FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT FROM EMPLOYEE2
WHERE DEPARTMENT IN  ('Finance','Marketing','IT');


SELECT*FROM EMPLOYEE2
WHERE EMAIL IS NULL;

SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEE2
ORDER BY SALARY DESC; 

SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEE2
ORDER BY SALARY DESC
LIMIT 5;

SELECT DISTINCT DEPARTMENT FROM EMPLOYEE2;

