DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS(
 PRODUCT_ID SERIAL PRIMARY KEY,
 PRODUCT_NAME VARCHAR(100),
 CATEGORY VARCHAR(50),
 PRICE NUMERIC(10,2),
 QUANTITY INT,
 ADDED_DATE DATE,
 DISCOUNT_RATE NUMERIC(5,2)
);

INSERT INTO PRODUCTS(PRODUCT_NAME,CATEGORY,PRICE,QUANTITY,ADDED_DATE,DISCOUNT_RATE)
VALUES('LAPTOP','ELECTRONICS','75000.50',10,'2024-01-15',10.00),
      ('SMARTPHONE','ELECTRONICS','45000.99',25,'2024-02-21',5.00),
	  ('HEADPHONES','ACCESSORIES','1500.75',50,'2024-03-05',15.00),
      ('0FFICE CHAIR','FURNITURE','5500.00',20,'2023-12-01',20.00),
      ('DESK','FURNITURE','8000.00',15,'2023-11-20',12.00),
      ('MONITOR','ELECTRONICS','12000.00',8,'2024-02-21',8.00),
	  ('PRINTER','ELECTRONICS','9500.50',5,'2024-03-05',7.50),
      ('MOUSE','ACCESSORIES','1250.00',40,'2023-12-01',10.00),
      ('KEYBOARD','ACCESSORIES','1250.00',35,'2024-03-18',10.00),
      ('TABLET','ELECTRONICS','30000.00',12,'2024-02-28',5.00);
SELECT*FROM PRODUCTS;

SELECT SUM(QUANTITY) AS TOTAL_QUANTITY
FROM PRODUCTS;

SELECT SUM(QUANTITY) AS ELECTRONICS_TOTAL_QUANTITY
FROM PRODUCTS
WHERE CATEGORY='ELECTRONICS' AND PRICE>20000;

SELECT COUNT(*) AS TOTAL_PRODUCTS 
FROM PRODUCTS;

SELECT COUNT(*) AS TOTAL_PRODUCTS 
FROM PRODUCTS
WHERE PRODUCT_NAME LIKE '%PHONE%'

SELECT AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS;

SELECT AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS
WHERE CATEGORY='ACCESSORIES';

SELECT MAX(PRICE) AS MAX_PRICE,
       MIN(PRICE) AS MIN_PRICE
FROM PRODUCTS;

SELECT * FROM PRODUCTS;
SELECT UPPER(CATEGORY) AS UPPERCASE
FROM PRODUCTS;
SELECT LOWER(CATEGORY) AS LOWERCASE
FROM PRODUCTS;
SELECT LENGTH(CATEGORY) AS LENGTH_NUMBERS
FROM PRODUCTS;  
SELECT CONCAT(PRODUCT_NAME,'-',CATEGORY) AS COMBINATION
FROM PRODUCTS;
SELECT SUBSTRING(PRODUCT_NAME,1,5) AS SHORT_NAME
FROM PRODUCTS;

SELECT TRIM('       MONITOR     ') AS TRIM_TEXT;
SELECT REPLACE(PRODUCT_NAME,'PHONE','DEVICE') AS UPDATED
FROM PRODUCTS;

SELECT NOW() AS CURRENT_TIME;
SELECT CURRENT_DATE AS DATE_NUMBER;
SELECT ADDED_DATE, (CURRENT_DATE-ADDED_DATE) AS CURRENT_DATE
FROM PRODUCTS;
SELECT PRODUCT_NAME,
EXTRACT(YEAR FROM ADDED_DATE) AS YEAR,
EXTRACT(MONTH FROM ADDED_DATE) AS MONTH,
EXTRACT(DAY FROM ADDED_DATE) AS DAY
FROM PRODUCTS;

SELECT PRODUCT_NAME,
AGE(CURRENT_DATE,ADDED_DATE) AS AGE_SINCE_ADDED
FROM PRODUCTS; 
SELECT*FROM PRODUCTS;
SELECT PRODUCT_NAME,PRICE,
     CASE
	 WHEN PRICE>=50000 THEN 'EXPENSIVE'
	 WHEN PRICE>=10000 AND PRICE<=49999 THEN 'MODERATE'
	 ELSE 'AFFORDABLE'
	 END AS AFFORADABLE_PRICE
FROM PRODUCTS;

SELECT PRODUCT_NAME ,QUANTITY,
       CASE 
	   WHEN QUANTITY>=10 THEN 'IN STOCK'
	   WHEN QUANTITY>=5 AND QUANTITY<=9 THEN 'LIMITED STOCK'
	   ELSE 'OUT OF STOCK'
	   END AS QUANTITY_STOCK
FROM PRODUCTS;

ALTER TABLE PRODUCTS 
ADD COLUMN DISCOUNT_PRICE NUMERIC(10,2); 
UPDATE PRODUCTS
SET DISCOUNT_PRICE=PRICE*0.9
WHERE PRODUCT_NAME  NOT IN('LAPTOP','DESK');

SELECT PRODUCT_NAME,
COALESCE(DISCOUNT_PRICE,PRICE)
FROM PRODUCTS;
SELECT PRODUCT_NAME,CATEGORY,PRICE,
ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS ROW_NUM
FROM PRODUCTS;
SELECT PRODUCT_NAME,CATEGORY,PRICE,
SUM(PRICE) OVER(PARTITION BY CATEGORY ORDER BY PRICE ASC) AS ROW_NUM
FROM PRODUCTS;

