DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
 BOOK_ID SERIAL PRIMARY KEY,
 TITLE VARCHAR(100),
 AUTHOR VARCHAR(100),
 GENRE VARCHAR(100),
 PUBLISHED_YEAR INT,
 PRICE NUMERIC(10,2),
 STOCK INT
);

DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS(
 CUSTOMER_ID SERIAL PRIMARY KEY,
 NAME VARCHAR(100),
 EMAIL VARCHAR(100),
 PHONE VARCHAR(15),
 CITY VARCHAR(100),
 COUNTRY VARCHAR(100)
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(
 ORDER_ID SERIAL PRIMARY KEY,
 CUSTOMER_ID INT REFERENCES CUSTOMERS(CUSTOMER_ID),
 BOOK_ID INT REFERENCES BOOKS(BOOK_ID),
 ORDER_DATE DATE,
 QUANTITY INT,
 TOTAL_AMOUNT NUMERIC(10,2)
);

SELECT*FROM BOOKS;
SELECT*FROM CUSTOMERS;
SELECT*FROM ORDERS;

--RETRIEVE ALL BOOKS IN THE FICTION GENRE 
SELECT*FROM BOOKS 
WHERE GENRE='Fiction';

--FIND BOOKS PUBLISHED AFTER THE YEAR 1950
SELECT*FROM BOOKS
WHERE PUBLISHED_YEAR>1950;

--LIST ALL CUSTOMERS FROM THE CANADA 
SELECT*FROM CUSTOMERS 
WHERE COUNTRY='Canada';

--SHOW ORDERS PLACED IN NOVEMBER 2023 
SELECT*FROM ORDERS 
WHERE ORDER_DATE BETWEEN '2023-11-01' AND '2023-11-30';

--RETRIEVE THE TOTAL STOCK OF BOOKS AVAILABLE
SELECT SUM(STOCK) AS TOTAL_STOCK FROM BOOKS;

--FIND THE DETAILS OF THE MOST EXPENSIVE BOOK 
SELECT*FROM BOOKS 
ORDER BY PRICE DESC
LIMIT 1;

--SHOW ALL CUSTOMERS WHO ORDERED MORE THAN 1 QUANTITY OF A BOOK 
SELECT C.NAME,O.QUANTITY
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE O.QUANTITY>1;

--RETRIEVE ALL ORDERS WHERE THE TOTAL AMOUNT EXCEEDS $20
SELECT*FROM ORDERS
WHERE TOTAL_AMOUNT>20;

--LIST ALL GENRES AVAILABLE IN THE BOOKS TABLE 
SELECT DISTINCT GENRE FROM BOOKS;

--FIND THE BOOK WITH THE LOWEST STOCK
SELECT*FROM BOOKS 
ORDER BY STOCK ASC
LIMIT 1;

--CALCULATE THE TOTAL REVENUE GENERATED FROM ALL ORDERS 
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM ORDERS;

--RETRIEVE THE TOTAL NUMBER OF BOOKS SOLD FOR EACH GENRE 
SELECT B.GENRE,SUM(O.QUANTITY) AS TOTAL_BOOKS_SOLD
FROM BOOKS B
JOIN ORDERS O
ON B.BOOK_ID=O.BOOK_ID
GROUP BY B.GENRE;

--FIND THE AVERAGE PRICE OF BOOKS IN THE FANTASY GENRE  
SELECT AVG(PRICE) AS AVG_PRICE FROM BOOKS 
WHERE GENRE='Fantasy';

--LIST CUSTOMERS WHO HAVE PLACED AT LEAST 2 ORDERS
SELECT CUSTOMER_ID,COUNT(ORDER_ID) AS ORDER_COUNT
FROM ORDERS
GROUP BY CUSTOMER_ID
HAVING COUNT(ORDER_ID)>=2;

--FIND THE MOST FREQUENTLY ORDERED BOOK
SELECT BOOK_ID,COUNT(ORDER_ID) AS ORDER_COUNT
FROM ORDERS
GROUP BY BOOK_ID 
ORDER BY COUNT(ORDER_ID) DESC
LIMIT 1

--SHOW THE TOP 3 MOST EXPENSIVE BOOK OF FANTASY GENRE 
SELECT*FROM BOOKS 
WHERE GENRE='Fantasy'
ORDER BY PRICE DESC
LIMIT 3;

--RETRIEVE THE TOTAL QUANTITY OF BOOKS SOLD BY EACH AUTHOR 
SELECT B.AUTHOR,SUM(O.QUANTITY) AS TOTAL_QUANTITY
FROM BOOKS B
JOIN ORDERS O
ON B.BOOK_ID=O.BOOK_ID
GROUP BY B.AUTHOR;

--LIST THE CITIES WHERE CUSTOMERS WHO SPENT OVER $30 ARE LOCATED 
SELECT DISTINCT C.CITY,O.TOTAL_AMOUNT
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
WHERE TOTAL_AMOUNT>300;

--FIND THE CUSTOMER WHO SPENT THE MOST ON ORDERS 
SELECT C.NAME,C.CUSTOMER_ID,SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT 
FROM CUSTOMERS C
JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY TOTAL_AMOUNT DESC
LIMIT 1;
































