DROP TABLE IF EXISTS STUDENTS_2023;
CREATE TABLE STUDENTS_2023(
 STUDENT_ID INT PRIMARY KEY,
 STUDENT_NAME VARCHAR(100),
 COURSE VARCHAR(50)
);

INSERT INTO STUDENTS_2023(STUDENT_ID,STUDENT_NAME,COURSE)
VALUES(1,'AARAV SHARMA','COMPUTER SCIENCE'),
      (2,'ISHITA VERMA','MECHANICAL ENGINEERING'),
	  (3,'KABIR PATEL','ELECTRONICS'),
	  (4,'ANANYA DESAI','CIVIL ENGINEERING'),
	  (5,'RAHUL GUPTE','COMPUTER SCIENCE');

SELECT*FROM STUDENTS_2023;
DROP TABLE IF EXISTS STUDENTS_2024;
CREATE TABLE STUDENTS_2024(
 STUDENT_ID INT PRIMARY KEY,
 STUDENT_NAME VARCHAR(100),
 COURSE VARCHAR(50)
);

INSERT INTO STUDENTS_2024(STUDENT_ID,STUDENT_NAME,COURSE)
VALUES(3,'KABIR PATEL','ELECTRONICS'),
      (4,'ANANYA DESAI','CIVIL ENGINEERING'),
	  (6,'MEERA RAO','COMPUTER SCIENCE'),
	  (7,'VIKRAM SINGH','MATHEMATICS'),
	  (8,'SANYA KAPOOR','PHYSICS');

SELECT*FROM STUDENTS_2024;

SELECT STUDENT_NAME,COURSE FROM STUDENTS_2023
UNION
SELECT STUDENT_NAME,COURSE FROM STUDENTS_2024;

SELECT STUDENT_NAME,COURSE FROM STUDENTS_2023
UNION ALL
SELECT STUDENT_NAME,COURSE FROM STUDENTS_2024;

SELECT STUDENT_NAME,COURSE FROM STUDENTS_2023
INTERSECT
SELECT STUDENT_NAME,COURSE FROM STUDENTS_2024;

SELECT STUDENT_NAME,COURSE FROM STUDENTS_2023
EXCEPT
SELECT STUDENT_NAME,COURSE FROM STUDENTS_2024;

