DROP TABLE IF EXISTS EMPLOYEE3;
CREATE TABLE EMPLOYEE3(
 EMPLOYEE_ID INT PRIMARY KEY,
 FIRST_NAME VARCHAR(50) NOT NULL,
 LAST_NAME VARCHAR(50) NOT NULL,
 DEPARTMENT_ID INT
);
INSERT INTO EMPLOYEE3(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID)
VALUES(1,'RAHUL','SHARMA',101),
      (2,'PRIYA','MEHTA',102),
	  (3,'ANKIT','VERMA',103),
      (4,'SIMRAN','KAUR',NULL),
	  (5,'AMAN','SINGH',101);
DROP TABLE IF EXISTS DEPARTMENTS;
CREATE TABLE DEPARTMENTS(
 DEPARTMENT_ID INT PRIMARY KEY,
 DEPARTMENT_NAME VARCHAR(50)
);   
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES(101,'SALES'),
      (102,'MARKETING'),
	  (103,'IT'),
	  (104,'HR');

SELECT*FROM EMPLOYEE3;
SELECT*FROM DEPARTMENTS;

SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEE3 E
INNER JOIN 
DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;


SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEE3 E
LEFT JOIN 
DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;


SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEE3 E
FULL OUTER JOIN  
DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM EMPLOYEE3 E
CROSS JOIN
DEPARTMENTS D;








